site_name: routelit
repo_url: https://github.com/routelit/routelit
site_url: https://routelit.io
site_description: Project to build easy user interfaces, framework agnostic
site_author: Rolando Gómez Tabar
edit_uri: edit/main/docs/
repo_name: routelit/routelit
copyright: Maintained by <a href="https://routelit.io">routelit</a>.

nav:
  - Home: index.md
  - Modules: modules.md
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: ["src"]
theme:
  name: material
  feature:
    tabs: true
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: deep orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: deep orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/routelit/routelit
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/routelit

markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
